### ISSUE TITLE
Mixed content error message

### ISSUE THREAD

**Issue by ckbraman** [j26design/Master-Page-Premium#4]
It seems that your widget is loading my favicons over a HTTP while my site is configured to load via HTTPS, resulting in a mixed content error message in Google Chrome Developer Tools. Please see for clarification: http://bit.ly/2HmkAWt.

(Regarding the nature of the error, here is a link from Google: https://developers.google.c...

My index.html file is providing a direct link, so I need to know what I need to be able to do to replace http with https to fix the issue.

Please advise. Thanks.

**Comment by jp26jp** [comment]
This is because https isn't being specified when you upload your site. Make sure you're specifying the correct URL when you upload your site. [See an example here](https://www.j-26.com/blog/5-step-guide-to-getting-your-adobe-muse-site-indexed/#step-2-choose-your-preferred-url-and-stick-with-it).
